name: Deploy Metadata

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify secret
        run: |
          if [ -z "${{ secrets.SF_AUTH_URL }}" ]; then
            echo "SF_AUTH_URL secret is required."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate org
        shell: bash
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias github-actions --set-default

      - name: Deploy metadata
        run: sf project deploy start --target-org github-actions --source-dir force-app --test-level NoTestRun
